### ISSUE TITLE
Benchmark 8 results page

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#1053]
For consistency with the other benchmarks, I would call them

"8a" instead of "2.1"
"8b" instead of "2.2"
"8c" instead of "2.3"
"8d" instead of "2.4"

8a: phase fraction X and total free energy F as functions of time t for three different initial radii.
Desired plots as in Figure 1

8b: phase fraction X and total free energy F as functions of time t. Snapshot at t=80.
Desired plots as in Figure 2.

8c: phase fraction X and total free energy F as functions of time t. Snapshot at t=80.
Desired plots as in Figure 3.

8d: phase fraction X as function of time t and snapshots at t=5000 for three different values of driving force.
Desired plots as in Figure 3.
Might later add free energy F as function of time t, but not immediately clear how to do that.

- Jon

Example data: [stats.txt](https://github.com/usnistgov/pfhub/files/3735359/stats.txt)

Example image:
![t-80 0](https://user-images.githubusercontent.com/1986844/66938477-396aff80-f00f-11e9-8c21-b59356a3b0e0.png)

**Comment by wd15** [comment]
- [ ] check BM8 using the upload form
 - [ ] create a meta.yaml file for test data for BM8
 - [ ] implement a comparison page for all four variations
 - [ ] enable TSV via the app
 - [ ] remove spaces in CSV files

**Comment by wd15** [comment]
@guyer, @tkphd: I'm confused about this. It seems that there are 3 variations for the first and fourth variation. That makes 8 variations total, not 4. Is that correct?

**Comment by tkphd** [comment]
Commented in slack but I'll reiterate here: good point about code verification *vs.* nucleation study. These should be refined to just one particle radius (8a) and one driving force (8d) for four variants, at *most*.

**Comment by wd15** [comment]
@guyer, FYI, for future reference TSV files like [stats.txt](https://github.com/usnistgov/pfhub/files/3735359/stats.txt) should have the header row formatted as tsv also. I couldn't figure out why this wasn't working initially.

**Comment by wd15** [comment]
Done with #1056

**Comment by wd15** [comment]
Needs some more cleaning up to actually match the spec

Example data: https://github.com/guyer/phasefieldbenchmark-8
