### ISSUE TITLE
Ensure all box data is backed up

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#1137]

**Comment by tkphd** [comment]
Does this mean setting the retention policy in Box to indefinite, replicating all Box data on another service, or snapshotting all Box data to track history?

**Comment by wd15** [comment]
I'm not sure. It's more discussing with Justin Senseney about where the data is and how NIST is dealing with these issues. I wasn't planning on implementing anything myself necessarily. Also trying to figure out how to view the data files on Box and clean things up if necessary which I'm not sure how to do currently.

**Comment by wd15** [comment]
This, I think, is irrelevant. I'll trust box to keep data for time being and once MDF is implemented I won't have to worry about it. Also, we're currently no backing up any data anyway so nothing is regressing.
