### ISSUE TITLE
Set up code repository to accompany Nucleation BM paper

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#1209]
Action items to implement

 - [ ] Set up repository at @wd15 or @guyer user area to start and then move to usnistgov once finished @wd15
 - [x] Add initial fipy files to repository @guyer
 - [ ] Contact all authors to add their initial submissions @wd15
 - [ ] Try and Dockerize one of the fipy simulations and add README @wd15
 - [ ] Try and add an annotated example from BM8 for one of the simualtions @wd15, @guyer 
 - [ ] Add Wenkun's MOOSE input files + explanation, @wuwenkun
 - [ ] Try and dockerize the MOOSE example, @wd15, @wuwenkun + others
 - [ ] Annotated example with MOOSE??? @wuwenkun, @wd15
 - [ ] Try and get the PRISMS and other code included once we have a structures @wd15, @wuwenkun, @guyer

**Comment by wd15** [comment]
@guyer, can you dump your FiPy nucleation files in a repository (either guyer or usnistgov, whichever you think)? I'm happy to clean it up and deal with the container issue is we decide to do that and get the other authors to contribute.

**Comment by guyer** [comment]
It's at https://github.com/guyer/phasefieldbenchmark-8
