### ISSUE TITLE
Set up infrastructure for upload from issue template

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#1299]
Rough work plan:

 - [x] Make python-pfhub read from list of meta.yaml's located at any location
   - [x] ensure all the tests pass
   - [x] check that docstrings are adequate for new functions
   - [x] make sure simulation_list.yaml lists local files where possible  
   - [x] start a PR for these changes to make sure the tests all pass
 - [x] set up issue template
 - [x] make the upload issue open a github action that reads the data 
 - [ ] clean up bug issue template to be appropriate (in #1331 awaiting approval)
 - [x] make the issue submission github action open a PR with the issue data
 - [x] ensure that only upload issues result in PRs
 - [x] allow resubmission of issues
 - [x] place message back into issue with link to PR (make sure that the PR has the link to the issue)
 - [x] update list of simulations 
 - [ ] clean up the upload issue to gather all the appropriate data, including the data locations (including some of the boxes in codemeta)
   - [x] use envsubst 
   - [x] make implementation complete
   - [x] in the envsubst step check that the envs are not required to simplify
   - [x] timestamp from issue
   - [x] name and email
   - [ ] ask about hardware
   - [ ] See Trevor comment below for what should be in included 
   - [x] make all dropdowns alphanumeric ordering
   - [ ] make the data section work
     - [ ] 2D, 3D, media boxes (key, value pairs as well, both options)
     - [ ] different template for each benchmark
   - [ ] add codemeta box
   - [ ] github actions for url data type checking (and other linting of data)
 - [ ] Set up a simple example repository and ensure uploads work correctly
   - [ ]  https://zenodo.org/communities/pfhub?page=1&size=20 (use this)
 - [ ] Use codemeta.json from upload repository to get more data (see below)
 - [ ] FAIR check (Trevor can guide me or help)
   - [ ] use [codemeta generator](https://codemeta.github.io/codemeta-generator/meta)? Is this feasible in some way?
   - [ ] can we force codemeta on people as a requirement?
 - [ ] allow resubmission of issues
 - [ ] allow populating of issue from from existing meta.yaml  
 - [ ] an issue template for each upload and corresponding meta.yaml.template

Old ideas:

 - [ ] Lint schema maybe, see [this](https://json-schema.org/implementations.html)
 - [ ] ensure an action is initiated when pinged and the notebooks are rebuilt
 - [ ] harvest meta-data
 - [ ] generate an individual notebook for the simulation
 - [ ] run a FAIR check tool for each repository and include badges in generated notebook (or table)
 - [ ] run the FAIR checker on the example repository
 - [ ] work on a new standard for the meta data
 - [ ] git lfs prototype

## Questions
 
 - Could the yaml file go anywhere, not just in a github repository? No, decided that it should go in phfub for now.
 - Should subsequent submissions for the same issue generate a new PR?

## Schemas

These could either be used in the phhub store or in the upload repo. Still getting that straight.

 - Software code schema: https://schema.org/SoftwareSourceCode
 - ASDF Schema: https://asdf-standard.readthedocs.io/en/1.5.0/schemas.html
 - Boutiques schema
 - codemeta.yaml or json? It has run-time environment box and versioning box, which are both useful to us.

## Goal

Long term we want the upload form to ask as little as possible and infer as much as possible.

**Comment by tkphd** [comment]
Additional thoughts: CodeMeta is great! Here's its [schema](https://raw.githubusercontent.com/codemeta/codemeta/2.0/codemeta.jsonld).

Each implementation repository should have a `codemeta.json`: generate one easily by filling in as much of the [CodeMeta Generator](https://codemeta.github.io/codemeta-generator/) as possible. By default, this populates author, license, and URL/DOI information. It does not capture framework information, though it could (using the schema, add a section to your JSON for `runtimePlatform` --- JVM or .NET is the example, but MOOSE or PRISMS-PF or FiPy would fit just as well; then add a `downloadUrl` and `version` field in the dict).

Is there an equivalent for data? ... or is that what we're going to discuss? Is there an implementation of Andrea Medina-Smith's [*Controlled Vocabulary and Metadata Schema for Materials Science Data Discovery*](https://doi.org/10.5334/dsj-2021-018)?

Things we might want to collect:

- [ ] URL of the implementation repository (GitHub or any web address)
    - [ ] Sub-directory containing `codemeta.json`, if not at the top level
    - [ ] Sub-directory for the implementation source code, if not at the top level
- [ ] Name and version of the software framework, if not present in `codemeta.json`
- [ ] URL for the data repository (any web address)
    - [ ]  Sub-directory for data, if applicable

**Comment by wd15** [comment]
Closing this issue as we now have a [project for this](https://github.com/usnistgov/pfhub/projects/7).
