### ISSUE TITLE
[Bug]: broken links

### ISSUE THREAD

**Issue by tkphd** [usnistgov/pfhub#1328]
### Contact Details

trevor.keller@nist.gov

### What happened?

CI failures on PR #1320:

1. Coverage is not 100%
    ```output
    ----------- coverage: platform linux, python 3.8.9-final-0 -----------
    Name                Stmts   Miss  Cover   Missing
    -------------------------------------------------
    pfhub/conftest.py      30      0   100%
    pfhub/main.py         127      1    99%   109
    -------------------------------------------------
    TOTAL                 157      1    99%

    FAIL Required test coverage of 100% not reached. Total coverage: 99.36%
    ```
2. Broken links in DEVELOPMENT.md:
    * <https://guides.github.com/activities/forking/>
    * <https://help.github.com/articles/creating-a-pull-request/>
    * <https://help.github.com/articles/editing-files-in-another-user-s-repository/>
    * <https://help.github.com/articles/pushing-to-a-remote/>
3. Broken link in     simulations/upload.md:
    * <https://help.github.com/articles/fork-a-repo/>
4. test.py/test_csv():
    ```output
    AssertionError: assert False
    where False = pipe('https://drive.google.com/file/d/1F2Pzo2IYYPhPmU_mryjR6flz2vUDr5Zy/view?usp=sharing',
                       get, <function test_csv.<locals>.<lambda> at 0x7efd5de3a4d0>)
    ```

### Version

1.0.2 (Default)

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tkphd** [comment]
Possibly already handled by #1321?

**Comment by wd15** [comment]
Fixed now
