### ISSUE TITLE
[Upload]: demo

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#1402]
### Short Name of Upload

demo5

### GitHub Repository

https://github.com/usnistgov/hiperc

### GitHub Hash

b25b14acda7c5aef565cdbcfc88f2df3412dcc46

### Summary

HiPerC spinodal decomposition result using CUDA on a Tesla P100 with 9-point discrete Laplacian

### Benchmark ID

1b

### Benchmark Version

1

### Code Name

custom

### Free Energy URL

https://ndownloader.figshare.com/files/10030003

### Free Energy Columns

sim_time, free_energy

### Memory Usage

308224

### Wall Time

7388

### Simulation Time

200000

**Comment by pfhub** [comment]
Thanks for the upload! Your submission has opened pull-request #1403. Please follow up there. Wait for the build processes to complete and then follow the posted comments.

**Comment by pfhub** [comment]
Thanks for the upload! Your submission has opened pull-request #1403. Please follow up there. Wait for the build processes to complete and then follow the posted comments.

**Comment by pfhub** [comment]
Thanks for the upload! Your submission has opened pull-request #1403. Please follow up there. Wait for the build processes to complete and then follow the posted comments.

**Comment by pfhub** [comment]
Thanks for the upload! Your submission has opened pull-request #1403. Please follow up there. Wait for the build processes to complete and then follow the posted comments.

**Comment by pfhub** [comment]
Thanks for the upload! Your submission has opened pull-request #1403. Please follow up there. Wait for the build processes to complete and then follow the posted comments.
