### ISSUE TITLE
Update nucleation benchmark with José Mancias proposed changes

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#1463]
Hello all,
I wanted to follow up on my presentation during last week's CHIMAD
workshop. In this presentation, I suggested some changes to the
nucleation benchmark as it is written in PF-Hub. I also mentioned that
the work that we did to develop these suggestions was published in a
paper. I have attached both the paper and the presentation so that you
may reference these if you feel that you would like to implement some of
the changes on PF-Hub. A brief version of just the potential edits
described in the powerpoint presentation are included below:

   * Use periodic boundary conditions for parts 2 and 3
   * Change critical radius (r*) in part 3 to r* = 1.0
   * Calculate the avrami slope using a fitting range in the y-axis
     (log[-log{1-Y}]) in parts 2 and 3, the range -2 < log[-log{1-Y}] < 0
     worked well for us
   * Potentially increase the amount of simulations to increase
     statistical accuracy in parts 2 and 3 (this must be weighted against
     longer simulation times)

Just to be complete the doi is here:
https://doi.org/10.1007/s40192-022-00284-1
<https://doi.org/10.1007/s40192-022-00284-1>
The paper is also available on arxiv: https://arxiv.org/abs/2210.16866
<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Farxiv.org%2Fabs%2F2210.16866&data=05%7C01%7Cdaniel.wheeler%40nist.gov%7C1eae3f1e7dde4182d24408dabe61fa8b%7C2ab5d82fd8fa4797a93e054655c61dec%7C1%7C0%7C638031625343836871%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000%7C%7C%7C&sdata=tqK0kqWthEMFTP7RapA1LWPetRwkb%2F637BR%2FBdyjUe0%3D&reserved=0>
The code is available on GitHub:
https://github.com/joseam2/PF_Nucleation_Benchmark_Julia
<https://github.com/joseam2/PF_Nucleation_Benchmark_Julia>

If there are any questions or if I can help at all please let me know.
Thank you and all the best,

**Comment by tkphd** [comment]
Addressed by #1465 -- can we close this, or is further work pending?
