### ISSUE TITLE
Add a requirements pop out on the upload page

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#403]
- [ ] only allow the hackathon result for problems 3, 4, 5, and 6
 - [ ] only allow certain data type uploads based on problem ID

**Comment by stvdwtt** [comment]
I'd think that users should specify problem version number rather than "Published" or "Hackaton", to cope with evolution of the benchmarks. Maybe have the version number with "Publication" or "Hackaton" in parentheses:

v1.0 (Hackathon)
v1.1 (Publication)

**Comment by tkphd** [comment]
That requires users to know [semver](http://semver.org/). I think it's better to have the form provide a text description ("Hackathon" or "Published"), and assign the numerical version in the back-end (which it does).

**Comment by wd15** [comment]
Rather than making the form problem specific, I'm going to use add a data requirement, section for each problem, which will be a pop out on the upload page.

**Comment by tkphd** [comment]
Good idea, I like it.

**Comment by wd15** [comment]
This is mostly contained in #881
