### ISSUE TITLE
Submit to Journal of Open Source Software

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#441]

**Comment by wd15** [comment]
I've submitted. I think the summary is written after the paper is accepted. https://joss.theoj.org/papers/9518358ebc8b8043a05bcf4f87f7b0ec

**Comment by tkphd** [comment]
OK. Maybe double-check the [submission instructions](https://joss.readthedocs.io/en/latest/submitting.html)?

**Comment by wd15** [comment]
Right, I need to withdraw and write the paper.md

**Comment by wd15** [comment]
Submitted to JORS, #938
