### ISSUE TITLE
Upload a simulation using the MDF

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#490]
Upload a simulation using the Materials Data Facility. Include the following in the `meta.yaml`

 - free energy 
 - memory usage
 - run time

**Comment by wd15** [comment]
@amjokisaari, this one's for you!

**Comment by amjokisaari** [comment]
alright, @wd15 .  I gotta admit I looked at this and I'm not actually sure how you want me to do this.  Am I submitting a standard data set to the MDF Open Collection, and as part of that data set, I include a copy of the meta.yaml file that we have on the CHiMaD website?

**Comment by wd15** [comment]
@amjokisaari, I'm not entirely sure myself. I thought that you could submit the data to the MDF and then fill out a meta.yaml for the website. Does that make sense? The meta.yaml is in our repository for now. I think that indexing the meta.yaml is a separate issue that Ben will take care of.

**Comment by amjokisaari** [comment]
@wd15 , okay, so do an MDF upload like usual, then proceed to the website and do that like usual?  And link to the MDF upload?

**Comment by amjokisaari** [comment]
I forget - did we agree on a data set to try for this?  BM III first iteration (as done at the workshop) ?

**Comment by wd15** [comment]
Your choice regarding which benchmark.

**Comment by wd15** [comment]
Over a year old and nothing happened so closing
