### ISSUE TITLE
data storage options

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#491]
[GitHub gists](https://gist.github.com) should be considered *temporary*. Consider alternatives for storing and serving benchmark data for the website.

#### Compatible Services
- [x] [figshare](https://figshare.com) → [howto](https://github.com/usnistgov/pfhub/issues/491#issuecomment-353459760)
- [x] [Amazon S3](https://aws.amazon.com/s3) → [howto](https://github.com/usnistgov/pfhub/issues/491#issuecomment-353486891)
- [x] [Backblaze B2](https://www.backblaze.com/b2/cloud-storage.html) → [howto](https://github.com/usnistgov/pfhub/issues/491#issuecomment-352581961)
- [ ] [Mendeley Data](https://data.mendeley.com/)

#### Incompatible Services
- [ ] [dat](https://datproject.org/)
    - command-line only, p2p, uncertain longevity
- [x] [Dryad](http://datadryad.org/) ⇢ [howto](https://github.com/usnistgov/chimad-phase-field/issues/491#issuecomment-353477006)
    - $120 up front, scoped for publication datasets
- [ ] [Google Cloud](https://cloud.google.com)
    - Requires credit card up front; unknown fees after $300 "free" allocation expires.
- [x] [IPFS](https://ipfs.io/) → [howto](https://github.com/usnistgov/chimad-phase-field/issues/491#issuecomment-355376182)
    - Web3.0 version of a basement fileserver: antithesis of an archive
- [ ] [Materials Data Curation System (MDCS)](https://mgi.nist.gov/materials-data-curation-system)
    - Tedious configuration up front, unless benchmark developers supply a schema.
- [ ] [Materials Data Facility (MDF)](https://materialsdatafacility.org)
    - No HTTP data interface: requires a Globus endpoint on your machine and a Globus client on the webserver.
- [x] [Materials Data Repository](https://materialsdata.nist.gov) → [howto](https://github.com/usnistgov/chimad-phase-field/issues/491#issuecomment-355384517)
    - Incompatible CORS settings
- [x] [Open Science Framework](https://osf.io) → [howto](https://github.com/usnistgov/chimad-phase-field/issues/491#issuecomment-352598218)
    - Incompatible CORS settings
- [x] [Zenodo](https://zenodo.org) → [howto](https://github.com/usnistgov/chimad-phase-field/issues/491#issuecomment-353482051)
    - Incompatible CORS settings

*please edit this list at will*

**Comment by tkphd** [comment]
#### Backblaze B2
1. Create account on [backblaze](https://www.backblaze.com/b2)
2. Create a bucket marked "Public." You get 100 buckets per account, so don't get too granular with it.
3. Click the popup link to "Show Account ID and Application Key".
4. Create an application key.
5. Click your bucket's link to [CORS Rules](https://www.backblaze.com/b2/docs/cors_rules.html), and select "Share everything in this bucket with every origin" or specify "https://pages.nist.gov".
5. [Install](https://www.backblaze.com/b2/docs/quick_command_line.html) the `b2` command-line tool:
  `$ pip3 install b2`
6. Configure your bucket:
  `$ b2 authorize_account <AccountID>`
  `Backblaze application key:`
  `$ b2 list_buckets`
  `75cf92cc224d664bd62050912 allPublic hiperc-results`
7. Upload a file, using `/` in filenames to set folders.
  `$ b2 upload_file <bucket> <local-name> <b2-name>`
8. Access file on the Web:
  `https://f001.backblazeb2.com/file/<bucket>/<file>`
  e.g., https://f001.backblazeb2.com/file/hiperc-results/gpu-cuda-spinodal/free-energy.csv
9. Use the [Upload Form](https://pages.nist.gov/chimad-phase-field/simulations/upload_form/).
10. Wait for your pull request to be approved, then find your landing page. The data chart should show up!

**Comment by tkphd** [comment]
#### Open Science Framework
1. Create an account on [osf](https://osf.io).
2. Create a project.
3. Make the project public.
4. Add a component (folder).
5. Make it public.
6. Drag-and-drop to upload files into your chosen data provider (OSF Storage by default).
7. Open the "Files" tab, then select a file.
8. The URL of the file is `https://osf.io/<handle>/` where `<handle>` is a 5-character hash. The file can be accessed directly using this URL by appending "download":
`https://osf.io/<handle>/download`
e.g., https://osf.io/usdvc/download
9. Upload and retrieve handles for each file.
10. Use the [Upload Form](https://pages.nist.gov/chimad-phase-field/simulations/upload_form/).
11. Wait for your pull request to be approved, then find your landing page. The data chart should show up!

**Comment by tkphd** [comment]
#### Figshare: *Compatible* with PFhub as of 2017-12-21
1. Create an account on [figshare][fig].
2. Under "My Data", either "Create a New Item" or click the [octocat][git] to import from GitHub.
3. Drag-and-drop files into the upload box at the top of the dialog.
3. Fill in the metadata as you see fit. For "Category," I've been using *Numerical Solution of Differential and Integral Equations*, since there's no *Computational Materials Science* key available.
4. Click on the "Public" check box.
5. If the dataset is not simply for testing purposes, then go ahead and request a DOI for it.
6. Click "Publish." In so doing, you promise to keep these data publicly available forever.
7. Click on your new dataset or fileshare in the list.
8. Under each thumbnail, next to the file name, there's a ⬇ download link. The URL is `https://ndownloader.figshare.com/files/<handle>/` where `<handle>` is a numerical index. The file can be accessed directly using this URL, *e.g.*, https://ndownloader.figshare.com/files/10030006
9. Retrieve handles for each file.
10. Use the [Upload Form](https://pages.nist.gov/chimad-phase-field/simulations/upload_form/).
11. Wait for your pull request to be approved, then find your landing page.
12. The data chart should show up!

[fig]: https://figshare.com
[git]: https://github.com/logos

**Comment by tkphd** [comment]
#### Dryad: Presumed *Incompatible* with PFhub as of 2017-12-21

1. Create an account on [dryad][dryad].
2. Click "Submit Data Now!"
3. Choose a journal. If you have not submitted a manuscript already, either wait or select *Scientific Data* as a placeholder.
4. Pay $120.
5. Upload this comment with the rest of the process.

[dryad]: http://datadryad.org

**Comment by tkphd** [comment]
#### Zenodo: *Incompatible* with PFhub as of 2017-12-21.
1. Create an account on [zenodo][zen].
2. Click "Upload."
3. Drag-and-drop files into the upload box at the top of the page.
4. Click "Start Upload" to transmit your data.
5. Fill in the metadata as you see fit.
   - Select "PFhub" as the Community.
   - If you already have a DOI, add it as a "related identifier."
6. Click "Save."
7. Click "Publish." In so doing, you promise to keep these data publicly available forever.
8. Next to each file name, there's a download link. The URL is `https://zenodo.org/record/<handle>/files/<filename>` where `<handle>` is a numerical index. The file can be accessed directly using this URL, *e.g.*, https://zenodo.org/record/1124941/files/free-energy-9pt.csv
9. Retrieve the handle from a link.
10. Use the [Upload Form](https://pages.nist.gov/chimad-phase-field/simulations/upload_form/).
11. Wait for your pull request to be approved, then find your landing page.
12. ~The data chart should show up!~ 
    - Zenodo does not support custom [CORS][cors] access controls.

[cors]: https://enable-cors.org/
[zen]: https://zenodo.org/

**Comment by tkphd** [comment]
#### Amazon S3
1. Create an account on [S3][aws].
2. Create a bucket.
    - Select the region nearest to you.
    - Enable versioning. Accept other property defaults.
    - Grant public read-access to the bucket.
3. Upload data into the bucket.
    - Click on the bucket name.
    - Drag-and-drop files into the upload box.
    - Click "Next."
    - Grant public read access to the object.
    - Choose "Standard" storage class and no encryption.
4. Open the bucket's "Permissions" tab.
5. Click on the "CORS configuration" button.
    - Change the last line of content from `<AllowedHeader>Authorization</AllowedHeader>` to
        `<AllowedHeader>*</AllowedHeader>`
    - Save the config.
    - Your data will not be plotted unless you do this!
6. Each file has a unique URL of the form `https://s3.<region>.amazonaws.com/<bucket>/<filename>`, *e.g.* https://s3.us-east-2.amazonaws.com/hiperc-results/free-energy-9pt.csv
7. Use the [Upload Form](https://pages.nist.gov/chimad-phase-field/simulations/upload_form/).
8. Wait for your pull request to be approved, then find your landing page.
9. The data chart should show up!

[aws]: https://aws.amazon.com/s3

**Comment by tkphd** [comment]
#### IPFS: *Compatible* with PFhub as of 2018-01-04
0. Follow the [guide](https://ipfs.io/docs/getting-started/).
1. Install and initialize [go-ipfs](https://ipfs.io/docs/install/).
2. Add your files to the IPFS, wrapped in a directory (`-w` flag), *e.g.*
```
$ ipfs add -w free-energy-9pt.csv spinodal.0000000.png spinodal.0005000.png \
              spinodal.0010000.png spinodal.0020000.png spinodal.0050000.png \
              spinodal.0100000.png spinodal.0150000.png spinodal.0200000.png
added QmYLjPGKKTmxHyeSpFD3EVm1i31eXGwxWNg5Mpn6Uhg6zS free-energy-9pt.csv
added QmNzGWUSZNJcX66Vt23k8beusFW3ESPAFiewQkPaC5ctQp spinodal.0000000.png
added QmRjaN62XaPppcJ48zRipY7nQAHMbZwCmWs2EHf52faiPv spinodal.0005000.png
added QmTxpiKhYgmuLsKbptGCRr5p5p5GQ3if4fa7EVNx3wpxWS spinodal.0010000.png
added QmZxzNKrrsBK5ccYpTAs5fWbGXbdJxxxbUzfTck7NYaauj spinodal.0020000.png
added QmarVLVwzsoGgMN9bofzyH3z6oyBwEoskCvNLPgvMCMPJN spinodal.0050000.png
added QmQQKYNiLauKJsX8EbH5zwmX6CFbqfhUQpERpGUZA6b1FP spinodal.0100000.png
added Qmb2eiqcAqmRNAau3csK3MZVMqihVzGgdA713FgESSskBZ spinodal.0150000.png
added QmXrFA4JZCUsjbLgoMoCMKk7v3Dv2bnKvCspBbkLPG8KmR spinodal.0200000.png
added Qma8jtcBZK3zjDV1UeQhbrX3W6wLrEKBcVAV9VyGfns39s 
```
3. The last hash (`Qma8jtcBZK3zjDV1UeQhbrX3W6wLrEKBcVAV9VyGfns39s`) refers to the directory, and is the permanent identifier for this dataset.
4. This is a local store, only. To publish your data, run
```
$ ipfs daemon &
Initializing daemon...
Adjusting current ulimit to 2048...
Successfully raised file descriptor limit to 2048.
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/129.6.196.57/tcp/4001
Swarm listening on /ip4/172.17.42.1/tcp/4001
Swarm listening on /ip6/::1/tcp/4001
Swarm listening on /p2p-circuit/ipfs/<node>
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/129.6.196.57/tcp/4001
Swarm announcing /ip4/129.6.196.57/tcp/4001
Swarm announcing /ip4/172.17.42.1/tcp/4001
Swarm announcing /ip6/::1/tcp/4001
API server listening on /ip4/127.0.0.1/tcp/5001
Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080
Daemon is ready
$ ipfs swarm peers
/ip4/104.131.131.82/tcp/4001/ipfs/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
/ip4/104.236.179.241/tcp/4001/ipfs/QmSoLPppuBtQSGwKDZT2M73ULpjvfd3aZ6ha4oFGL1KrGM
/ip4/128.199.219.111/tcp/4001/ipfs/QmSoLSafTMBsPKadTEgaXctDQVcqN88CNLHXMkTNwMKPnu
/ip4/178.62.158.247/tcp/4001/ipfs/QmSoLer265NRgSp2LA3dPaeykiS1J6DifTC88f5uVQKNAd
```
5. You may have to open the listening port (4001 by default) on your router, firewall, iptables, etc.
6. Each file has a unique URL of the form `https://ipfs.io/<hash>/<filename>`, *e.g.* https://ipfs.io/ipfs/Qma8jtcBZK3zjDV1UeQhbrX3W6wLrEKBcVAV9VyGfns39s/free-energy-9pt.csv
7. *If* your local machine is visible to the IPFS swarm, then your files will be available remotely: the above link is just a relay, not a server. So, if you're firewalled, or switch your machine off and don't autostart `ipfs daemon`, the data will be inaccessible.
8. Use the [Upload Form](https://pages.nist.gov/chimad-phase-field/simulations/upload_form/).
9. Wait for your pull request to be approved, then find your landing page.
10. The data chart should show up!

Note that, while it does technically work, this method of data storage is considered less reliable than a gist, or personal Google drive, etc. While the object-hash is a *permanent record* of the data, it is not a *persistent store*: there's a permanent address, but the underlying storage medium may be inaccessible. Only use this if you can commit to standing up a permanent, fault-tolerant, publicly-accessible data server.

**Comment by tkphd** [comment]
#### Materials Data Repository
1. Request an account from https://materialsdata.nist.gov
2. Login, and choose an open data store, *e.g.* [Computational File Repository / Other](https://materialsdata.nist.gov/handle/11256/12).
3. Click the link up top to submit a dataset.
4. Fill in the questionnaire, and upload your files one-at-a-time.
5. Wait for the dataset to undergo review.

**Comment by tkphd** [comment]
Synthesize data after [DataVerse summary](https://dataverse.org/blog/comparative-review-various-data-repositories), #462

**Comment by stvdwtt** [comment]
@tkphd Thanks for writing all of these up. I followed your directions for Backblaze B2, and it worked like a charm.

**Comment by tkphd** [comment]
That's great! Thanks for the feedback, @stvdwtt.

**Comment by wd15** [comment]
We might want to contact ODF to see if they know that they don't allow CORS or if no one has asked them

**Comment by wd15** [comment]
@tkphd: can we close this issue as we now have a wiki page with all this information present. I think this issue is no longer something we need to implement, but just a source of information so it could be closed.
