### ISSUE TITLE
review tutorial for contributors

### ISSUE THREAD

**Issue by tkphd** [usnistgov/pfhub#529]
Provide an outline of [Reviewable.io](https://reviewable.io) for contributors, in terms of its features, benefits over the GitHub tools, and a skeleton workflow. Provide references for further reading.

**Comment by tkphd** [comment]
@wd15 what would be the appropriate place for the workflow and guide for reviewing a pull request? The development page comes to mind, but there would be a fair amount of editing to get priorities in order. Reviewing a pull request can be considered as a task separate from development, especially if newcomers are doing the reviews. Anyway, thoughts?

**Comment by wd15** [comment]
@tkphd, let's just add it to the developer page for now or link to it from the developer page. We can think about readthedocs or something later.

**Comment by wd15** [comment]
See this for some guidance, https://help.github.com/articles/setting-guidelines-for-repository-contributors/

**Comment by wd15** [comment]
Possibly add both a pull request templated and an issue template, https://github.com/usnistgov/chimad-phase-field/community. The pull request template could have a succinct version of what's in the pull request guide.

**Comment by wd15** [comment]
A docker image might be an idea for reviewing pull requests, make it possible to click on a link in the pull request which fires up the site either locally or elsewhere just for the purposes of review.

**Comment by guyer** [comment]
Running the official [jekyll docker container](https://github.com/jekyll/docker) from within a `chimad-phase-field` working copy seems to "just work". 

```
docker run --rm   --volume="$PWD:/srv/jekyll" -p 4000:4000  -it jekyll/jekyll:$JEKYLL_VERSION   jekyll serve
```

**Comment by wd15** [comment]
@tkphd, can I prompt you on this one? Do you want to move it out of milestone 0.4.1 to 0.4.2?

**Comment by tkphd** [comment]
Hey @wd15, I'm working on it, thanks for the prompt.

- I'm having permissions problems on my workstation, so the jekyll-docker command doesn't "just work."
- It does work on my home machine; and, looking on [Docker hub](https://hub.docker.com/r/jekyll/jekyll/tags/), the command can be simplified to
  `docker run --rm --volume="$PWD:/srv/jekyll" -it jekyll/jekyll:stable jekyll build`
- I'll verify that the website is served at home, then document usage with a little more clarity (esp. the fact that one need not clone the git repo).

**Comment by tkphd** [comment]
- Permissions problems on my workstation trace back to my NFS-mounted `/home`. There is no apparent easy fix, so I'm using the more difficult old workflow at my desk.
- On my home desktop, the Docker workflow works just fine, and with port forwarding I can serve a pirate station to the WWW. @guyer's technique works great!

**Comment by wd15** [comment]
@tkphd, I don't think this is necessary anymore

**Comment by wd15** [comment]
We have the wiki pages now for contributing material. I don't expect people to contribute to the website unless they know what they're doing with Jekyll and Git etc

**Comment by wd15** [comment]
@tkphd, can we close this?
