### ISSUE TITLE
Move site to pfhub?

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#556]
Shall we move the repo to "usnistgov/pfhub" and use pfhub.org for the url?

**Comment by stvdwtt** [comment]
Assuming we go with the name, I say yes.

**Comment by wd15** [comment]
Also redirect from pfhub.org

**Comment by tkphd** [comment]
Re-posting from the [Gitter](https://gitter.im/usnistgov/chimad-phase-field) conversation:

> The problem with PFHub is not that a [website already exists](http://www.pfhub.com/), but rather that somebody [owns the trademark](http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4808:vm309n.2.1).
> - If we are committed to the name, we need to run it past the NIST attorneys, which will probably take a while and may result in a flat "no". @tkphd has already reached out to them.
> - If not, would an alternative such as PhaseHub be suitable?
>   - [It's not trademarked](http://tmsearch.uspto.gov/bin/showfield?f=toc&state=4808%3Avm309n.1.1&p_search=searchss&p_L=50&BackReference=&p_plural=yes&p_s_PARA1=&p_tagrepl~%3A=PARA1%24LD&expr=PARA1+AND+PARA2&p_s_PARA2=phasehub&p_tagrepl~%3A=PARA2%24COMB&p_op_ALL=AND&a_default=search&a_search=Submit+Query&a_search=Submit+Query)
>   - The website would be pages.nist.gov/phasehub, which is very close to our frontrunner
>   - "The Phase Field Community Hub" still clearly applies
>   - We won't be contributing hits to a spammy news site through errant web searches.

 
If you have ideas for an alternative name, please record them in [The List](https://etherpad.net/p/rename-chimad-phase-field). We might need to vote again.

**Comment by tkphd** [comment]
### PFHub is approved. Let's do it.

**Comment by tkphd** [comment]
Action completed on 1/16/2018.

**Comment by wd15** [comment]
@tkphd, not yet! few things to take care of.

 - [ ] ensure Travis points at pfhub
 - [ ] ensure staticman points at pfhub
 - [ ] update _config.yml
 - [ ] remove references to chimad-phase-field in repo
 - [ ] ensure that references to pfhub are stored in _config.yml, many places need updating
 - [ ] check with `grep -r --exclude-dir=.git --exclude-dir=hackathons --exclude="*.raw.html" --exclude="*~" --exclude-dir=".ipynb_checkpoints" --exclude-dir=_site chimad-phase-field .`

**Comment by tkphd** [comment]
Haha, was just looking at travis and realized this was prematurely closed. Sorry!
