### ISSUE TITLE
serve static profile photos

### ISSUE THREAD

**Issue by tkphd** [usnistgov/pfhub#564]
Some profile photos are hotlinked, esp. to GitHub avatars, which are subject to change. To ensure contributors are displayed with professional images, irrespective of changes to other services, all profile photos should be stored in and statically served from this repository. 

Community members should be following the directions and submitting preferred photos by email. Those with hotlinked avatars should be contacted and asked to supply replacement images.

**Comment by wd15** [comment]
@tkphd, did this one get fixed with #678?

**Comment by tkphd** [comment]
Mostly, yeah.
