### ISSUE TITLE
Add link to MRS write-up

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#570]
http://materials.typepad.com/mrs_meeting_scene/2017/11/tc05-uncertainty-quantification-in-multiscale-materials-simulation-1.html

**Comment by wd15** [comment]
@guyer, do you have the still slides for this talk? Could you publish them online somewhere?

**Comment by guyer** [comment]
Slide presentations by NIST staff must be ERBed before being posted to the public. I can start that process.

**Comment by wd15** [comment]
@guyer, did you every get anywhere with the ERBing?
