### ISSUE TITLE
Upload ribbon gets oogy when you zoom out

### ISSUE THREAD

**Issue by guyer** [usnistgov/pfhub#575]
Zoom Out in Chrome results in the purple upload ribbon looking undesirable

![image](https://user-images.githubusercontent.com/1830725/33619112-5ba4a5e4-d9b2-11e7-8120-543038069f8e.png)

**Comment by tkphd** [comment]
[Oogy?](https://www.goodreads.com/book/show/8105569-oogy)

**Comment by guyer** [comment]
I'm not sure what the zoom percentage is, but I agree this isn't a priority. 

It happens in Safari, too.

**Comment by wd15** [comment]
Looks ok to me in Chrome now
