### ISSUE TITLE
introductory documentation

### ISSUE THREAD

**Issue by tkphd** [usnistgov/pfhub#583]
link to exemplary documentation introducing phase-field methods and numerical concepts
- [ ] [FiPy 1D Diffusion][fipy]
- [ ] [MMSP Beginners Diffusion][mmsp]
- [ ] [MOOSE Fe-Cr Decomposition][moose]
- [ ] ...

[fipy]:      https://www.ctcms.nist.gov/fipy/examples/diffusion/generated/examples.diffusion.mesh1D.html
[mmsp]: https://github.com/mesoscale/mmsp/tree/develop/examples/beginners_diffusion
[moose]: http://mooseframework.org/wiki/MooseTutorials/IronChromiumDecomposition/

**Comment by wd15** [comment]
@tkphd, over a year old. I don't think this will ever happen.
