### ISSUE TITLE
textbook reviews

### ISSUE THREAD

**Issue by tkphd** [usnistgov/pfhub#585]
Summarize and comment on what users will get out of phase-field textbooks:
- [ ] Provatas and Elder, *Phase-Field Methods in Materials Science and Engineering*
- [ ] Binder, *Programming Phase-Field Modeling*
- [ ] ...

**Comment by wd15** [comment]
@tkphd: this one is old too -- is this a likely candidate to ever be done? Would you give it a finish date?

BTW, I'm reorganizing the milestones into meeting dates so they are more concrete.

**Comment by wd15** [comment]
@tkphd, shall we close this. Who has time to review text books???
