### ISSUE TITLE
update overview essay

### ISSUE THREAD

**Issue by tkphd** [usnistgov/pfhub#588]
The [extended essay](https://pages.nist.gov/chimad-phase-field/benchmarks/) includes language that requires maintenance any time a benchmark set is released. Suggested edits:
- [x] ~~provide links to codes mentioned by name~~
- [x] ~~provide NIST disclaimer if necessary~~
- [x] rephrase last paragraph, either describing the current state or (better) making a time-independent statement that links back to the updated list of benchmarks.

**Comment by wd15** [comment]
@tkphd, over a year old, can we close this?

**Comment by tkphd** [comment]
Nope, the final bullet point still needs to be addressed.

**Comment by wd15** [comment]
@tkphd, can you assign this a meeting milestone if you think you'll implement this.
