### ISSUE TITLE
community refresh

### ISSUE THREAD

**Issue by tkphd** [usnistgov/pfhub#589]
The biographical sketches posted on the [community page](https://pages.nist.gov/chimad-phase-field/community/) span a wide range of styles and depth. It would be more helpful, in keeping with our outreach and educational goals, to provide the following:
1. A statement of the member's institutional affiliation and areas of expertise.
2. If the member is also a developer, a list of codes with roles in each (lead, developer, moral support, ...).
3. A summary of topics the member would be comfortable fielding questions about from the general public.
4. A portrait image, to be cropped, stored and statically served from the website (since github avatars change #564).

*Updated bios can be sent to [me](https://pages.nist.gov/chimad-phase-field/community/#trevor-keller) by e-mail.*

**Comment by wd15** [comment]
@tkphd, has this one been done?

**Comment by tkphd** [comment]
Nope.

**Comment by wd15** [comment]
@tkphd, this is over a year old -- will anything ever happen on this?
