### ISSUE TITLE
plots come last on lander

### ISSUE THREAD

**Issue by tkphd** [usnistgov/pfhub#605]
When images are provided in `meta.yaml`, the free energy plot (etc.) gets displaced to the bottom of the page, *e.g.* on https://random-cat-604.surge.sh/simulations/hiperc_1b_cuda or https://pages.nist.gov/chimad-phase-field/simulations/hiperc_1b_cuda. It would be preferable to have images come after overview charts, rather than before.

**Comment by wd15** [comment]
Fixed with #962
