### ISSUE TITLE
Group plots on the individual simulation pages (low priority)

### ISSUE THREAD

**Issue by stvdwtt** [usnistgov/pfhub#733]
Currently, one is "featured" near the top and the rest are down at the bottom of the page. It would make sense to have them all together.

**Comment by tkphd** [comment]
... or to allow users to specify which figure to feature, on the upload form.

**Comment by wd15** [comment]
@stvdwtt: shall I go with Trevor's idea on this one? Is that alright? The point was to have one plot sort of showcased off to the side. If it can be specified like @tkphd suggests, would that be cool?

**Comment by stvdwtt** [comment]
I think having one plot showcased is fine, but I think it would be more intuitive for all of the individual simulation pages to look the same for a particular benchmark problem. That would mean setting it at the problem level not at the simulation level.

**Comment by wd15** [comment]
Right, makes sense. I was going to let the user choose in the upload form, but that is way more complicated requiring messing with the upload form and adding another field in the meta.yaml. I'll go with making the choice at the benchmark level based on the name of the data. Much easier.

**Comment by wd15** [comment]
Fixed with #977
