### ISSUE TITLE
Ensure that each simulation name is unique at upload

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#766]

**Comment by tkphd** [comment]
Maybe we should auto-generate simulation names from the gathered data, since the preferred names seem to be regular expressions of the form
```
software_problem_solver_githubHandle
```

**Comment by wd15** [comment]
Agreed. Each simulation record should be stored using a unique ID rather than the short name and the short name should be auto-generated from the metadata.

**Comment by wd15** [comment]
Now part of #888
