### ISSUE TITLE
Investigate slow / absent tex for benchmarks on Chrome

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#788]

**Comment by tkphd** [comment]
@wd15 does this issue affect all benchmarks, or a specific subset?
What does "slow" mean? Are particular LaTeX objects absent, or does nothing load?
Any tools we could use to compare load times on different OS/browser combinations?
Which browsers have been tested?
- [ ] Chrome
- [ ] Firefox
- [ ] Internet Explorer
- [ ] Opera
- [ ] Safari
- [ ] Vivaldi

**Comment by tkphd** [comment]
On Debian 9 (Stretch) with Google Chrome 66.0.3359.181 and Mozilla Firefox 52.8.0esr:

| TeX Renders?  | commit | Chrome | Firefox |
| ---                     | ---         | ---           | ---        |
| pages.nist.gov | 9e904f2 | no          | yes      |
| local build        | 9e904f2 | yes        | no        |
| surge.sh build  | 84615fc | yes        | yes      |

**Comment by tkphd** [comment]
Benchmark 4 appears to be a particular troublemaker.

**Comment by stvdwtt** [comment]
Computer 1
OS X: 10.11.6 (El Capitan)
Chrome: 66.0.3359.181

None of the LaTeX renders (or at least takes longer than about 1 minute, after which I closed the tabs).

Computer 2
OS X: 10.11.6 (El Capitan)
Chrome: 66.0.3325.181

Benchmark 1: Renders instantly
Benchmarks 2-7: Doesn't render

Previously it worked on both computers, although sometimes it took a 15 seconds or so for all the rendering to complete.

**Comment by wd15** [comment]
Fixed with #789
