### ISSUE TITLE
Confusing "Efficiency" plot axes

### ISSUE THREAD

**Issue by stvdwtt** [usnistgov/pfhub#829]
I think the choice of axes for the "Efficiency" plots is a bit confusing. A simulation is more efficient the lower it is on the y axis (ie it uses less memory), but is more efficient as it is higher on x axis (ie it can do more simulated time for a given amount of wall time). I think it would be clearer if one could use a "lower is good" or "higher is good" heuristic for both axes.

![image](https://user-images.githubusercontent.com/10517751/44670416-a200b280-a9f0-11e8-95fe-a7836c24d5da.png)

I propose calling the x axis "Normalized Wall Time" and have it be wall time divided by simulated time (the reciprocal of the current set up).  I realize that "Normalized Wall Time" could mean other things (eg accounting for number of cores or processor speed), so I'd also be fine just labeling it "Wall Time/Sim Time".

**Comment by wd15** [comment]
@stvdwtt, makes sense. Easy to change as well.
