### ISSUE TITLE
All MOOSE benchmarks uploaded by itg report virtual rather than physical memory

### ISSUE THREAD

**Issue by dschwen** [usnistgov/pfhub#878]
All benchmarks uploaded by @itgreenquist use a postprocessor to report memory usage that defaults to returning the _virtual_ memory used, rather than the _physical_ memory used. This results in an overestimation of MOOSE memory usage by an order of magnitude or more (this is operating system dependent, on macs it can be _a lot_ more).

**Comment by dschwen** [comment]
I put in a PR to MOOSE to change this default behavior: https://github.com/idaholab/moose/pull/12242

**Comment by wd15** [comment]
I think we need clearer instructions on the website about what to report.

**Comment by wd15** [comment]
@itgreenquist, for example, to update "itg_moose_1a", go to https://pages.nist.gov/pfhub/simulations/display/?sim=itg_moose_1a and click on "USE AS TEMPLATE FOR NEW SUBMISSION". All you need to do is then change the memory usage value and resubmit. The name of the new result will be itg_moose_1a_update, but I'll remove the _update when we're happy that it's correct.

**Comment by wd15** [comment]
@dschwen, @itgreenquist: can I close this?

**Comment by wd15** [comment]
Closing this now
