### ISSUE TITLE
Require github authentication in the form

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#885]

**Comment by tkphd** [comment]
Is this necessary? It's conceivable someone might prefer Mercurial to Git, and Bitbucket to GitHub, for example, and therefore not have credentials.

**Comment by wd15** [comment]
@tkphd, we use GitHub pull requests for our upload process. It's handy if the person uploading the data has a GitHub ID for communication purposes. The only way to really ensure that is via authentication. Authentication would also allow us to do more fancy interactions on the backend like automated actions that don't require a pull request.
