### ISSUE TITLE
Use unique ID for each simulation result and autogenerate simulation name

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#888]
The format can be
```
{code}_{benchmark id}_{version}_{sim name}_{first 8 digits of hash}
```
for example

**Comment by wd15** [comment]
Ensure that each simulation name is unique at upload, from #766

**Comment by wd15** [comment]
Have unique ID for directory names

**Comment by tkphd** [comment]
Bump.

**Comment by wd15** [comment]
Moved to the [upload project](https://github.com/usnistgov/pfhub/projects/7)
