### ISSUE TITLE
Add Slack group for PFHub 

### ISSUE THREAD

**Issue by wd15** [usnistgov/pfhub#939]
Gitter has issues such as privacy, search and sharing data. Slack may be better. We should try it.

**Comment by dschwen** [comment]
Do you have a link to read up on those issues?

**Comment by wd15** [comment]
@dschwen: I did read this last week, https://matthewrocklin.com/blog/2019/02/28/slack-github, which weirdly made me thing about why we might use Slack. I think Gitter is a bit open for our group since we often want to discuss things that are only really relevant to our group and which aren't relevant to the project. For example, during the Gov shutdown it would have been nice to discuss stuff that we really wouldn't want in an open forum that isn't necessarily related to the project.

Other links:

 - https://stackshare.io/stackups/gitter-vs-slack
 - https://medium.com/@russleyshaw/which-chat-platform-should-i-use-d73f22d558f3
 - https://medium.freecodecamp.org/so-yeah-we-tried-slack-and-we-deeply-regretted-it-391bcc714c81

After reading the above it makes me think that Gitter isn't that bad after all, but it wouldn't hurt to try Slack as a group.

**Comment by wd15** [comment]
Emailed Add about setting it up

**Comment by wd15** [comment]
Group is at pfhub.slack.com. Thanks to @guyer for this.

**Comment by dschwen** [comment]
Do we need to get added to this?

**Comment by wd15** [comment]
On Mon, Apr 22, 2019 at 4:12 PM Daniel Schwen <notifications@github.com> wrote:
>
> Do we need to get added to this?

I thought that you didn't like slack.

-- 
Daniel Wheeler

**Comment by dschwen** [comment]
? Ooookay. If the plan is to split the community ant not have everyone in one place I can delete my slack account...
