### ISSUE TITLE
Nix error cloning builder process

### ISSUE THREAD

**Issue by tkphd** [usnistgov/pfhub#944]
This is not a PFHub issue, but as it is a bug I encountered on both my Debian machines, I think it should be documented.

On Debian 9, the Nix installation throws an error:

```
$ bash <(curl https://nixos.org/nix/install)
copying Nix to /nix/store.................................
initialising Nix database...
Nix: creating `/.nix-profile
installing 'nix-2.2.1'
error: cloning builder process: Operation not permitted
error: unable to start build process
./install: unable to install Nix into your default profile
```

Following some Internet breadcrumbs, I came across the following [workaround](https://github.com/NixOS/nix/issues/2633#issuecomment-455788240)

```
$ sudo sysctl kernel.unprivileged_userns_clone=1
```

The referenced comment was made in response to an Arch Linux installation problem. It's unclear whether the root cause is a kernel version, or systemd, or what.

**Comment by wd15** [comment]
As there is a workaround and this isn't something that we can fix, can I close this.

**Comment by tkphd** [comment]
Yup, it'll be preserved here for reference.
